In [12]:
import subprocess
import pickle
import numpy as np

In [36]:
n_run = 100


In [38]:
# Original (ie performance should be comparable)
np.random.seed(11121)
for seed in np.random.randint(10**6, size = n_run):
    subprocess_args = ['python', '/home/t722s/Desktop/UniversalModels/OtherRepos/SAM-Med3D/validation.py', 
                        '--seed', str(seed),
                        '-vp', '/home/t722s/Desktop/Sam-Med3DTest/BratsMiniOld',
                        '-cp', '/home/t722s/Desktop/UniversalModels/TrainedModels/sam_med3d.pth',
                        '-tdp', '/home/t722s/Desktop/Datasets/BratsMiniOld/',
                        '--save_name', '/home/t722s/Desktop/Sam-Med3DTest/evalBrats/old.py']
    subprocess.run(subprocess_args,
                    stdout=subprocess.DEVNULL, 
                    stderr=subprocess.DEVNULL)

In [46]:
# My script, using the same algorithm as the original ie cropping around ground truth, interactive point generation, successive iterations feed one (new) point and the previous generated low res mask
np.random.seed(11121)
for seed in np.random.randint(10**6, size = n_run):
    point_generation_args = ['python', 'generate_points.py', \
        '-tdp', '/home/t722s/Desktop/Datasets/BratsMini/', \
        '-rp', '/home/t722s/Desktop/Sam-Med3DTest/evalBrats/', \
        '-nc', '5',
        '--seed', str(seed)]
    subprocess.run(point_generation_args,
                    stdout=subprocess.DEVNULL, 
                    stderr=subprocess.DEVNULL)
    validation_args = ['python', 'SAM-Med3D/validationTesting.py', 
                        '--seed', str(seed),
                        '-vp', '/home/t722s/Desktop/Sam-Med3DTest/BratsMini',
                        '-cp', '/home/t722s/Desktop/UniversalModels/TrainedModels/sam_med3d.pth',
                        '-tdp', '/home/t722s/Desktop/Datasets/BratsMini/',
                        '--eval_dir', '/home/t722s/Desktop/Sam-Med3DTest/evalBrats',
                        '-mrn',  'gt_crop_interactive',
                        '-i',
                        '-l'
                        ]
    subprocess.run(validation_args,
                    stdout=subprocess.DEVNULL, 
                    stderr=subprocess.DEVNULL)

In [59]:
# My script, using the same algorithm as the original ie cropping around ground truth, presupplied point generation, successive iterations feed one (new) point and the previous generated low
np.random.seed(11121)
for seed in np.random.randint(10**6, size = n_run):
    point_generation_args = ['python', 'generate_points.py', \
        '-tdp', '/home/t722s/Desktop/Datasets/BratsMini/', \
        '-rp', '/home/t722s/Desktop/Sam-Med3DTest/evalBrats/', \
        '-nc', '5',
        '--seed', str(seed)]
    subprocess.run(point_generation_args,
                    stdout=subprocess.DEVNULL, 
                    stderr=subprocess.DEVNULL)
    validation_args = ['python', 'SAM-Med3D/validationTesting.py', 
                        '--seed', str(seed),
                        '-vp', '/home/t722s/Desktop/Sam-Med3DTest/BratsMini',
                        '-cp', '/home/t722s/Desktop/UniversalModels/TrainedModels/sam_med3d.pth',
                        '-tdp', '/home/t722s/Desktop/Datasets/BratsMini/',
                        '--eval_dir', '/home/t722s/Desktop/Sam-Med3DTest/evalBrats',
                        '-mrn',  'gt_crop_not_interactive',
                        '-nc', '5',
                        '-l', 
                        ]
    subprocess.run(validation_args,
                    stdout=subprocess.DEVNULL, 
                    stderr=subprocess.DEVNULL)

In [60]:
# My script, using the same algorithm as the original crop around point mask, interactive point generation, successive iterations feed one (new) point and the previous generated low
np.random.seed(11121)
for seed in np.random.randint(10**6, size = n_run):
    point_generation_args = ['python', 'generate_points.py', \
        '-tdp', '/home/t722s/Desktop/Datasets/BratsMini/', \
        '-rp', '/home/t722s/Desktop/Sam-Med3DTest/evalBrats/', \
        '-nc', '5',
        '--seed', str(seed)]
    subprocess.run(point_generation_args,
                    stdout=subprocess.DEVNULL, 
                    stderr=subprocess.DEVNULL)
    validation_args = ['python', 'SAM-Med3D/validationTesting.py', 
                        '--seed', str(seed),
                        '-vp', '/home/t722s/Desktop/Sam-Med3DTest/BratsMini',
                        '-cp', '/home/t722s/Desktop/UniversalModels/TrainedModels/sam_med3d.pth',
                        '-tdp', '/home/t722s/Desktop/Datasets/BratsMini/',
                        '--eval_dir', '/home/t722s/Desktop/Sam-Med3DTest/evalBrats',
                        '-mrn',  'point_crop_interactive',
                        '-nc', '5',
                        '-i'
                        ]
    subprocess.run(validation_args,
                    stdout=subprocess.DEVNULL, 
                    stderr=subprocess.DEVNULL)

In [61]:
# My script, using the same algorithm as the original ie cropping around ground truth, presupplied point generation, successive iterations feed one (new) point and the previous generated low
np.random.seed(11121)
for seed in np.random.randint(10**6, size = n_run):
    point_generation_args = ['python', 'generate_points.py', \
        '-tdp', '/home/t722s/Desktop/Datasets/BratsMini/', \
        '-rp', '/home/t722s/Desktop/Sam-Med3DTest/evalBrats/', \
        '-nc', '5',
        '--seed', str(seed)]
    subprocess.run(point_generation_args,
                    stdout=subprocess.DEVNULL, 
                    stderr=subprocess.DEVNULL)
    validation_args = ['python', 'SAM-Med3D/validationTesting.py', 
                        '--seed', str(seed),
                        '-vp', '/home/t722s/Desktop/Sam-Med3DTest/BratsMini',
                        '-cp', '/home/t722s/Desktop/UniversalModels/TrainedModels/sam_med3d.pth',
                        '-tdp', '/home/t722s/Desktop/Datasets/BratsMini/',
                        '--eval_dir', '/home/t722s/Desktop/Sam-Med3DTest/evalBrats',
                        '-mrn',  'point_crop_not_interactive',
                        '-nc', '5',
                        ]
    subprocess.run(validation_args,
                    stdout=subprocess.DEVNULL, 
                    stderr=subprocess.DEVNULL)

[[64 57 60]
 [75 55 65]
 [71 75 63]
 [61 51 68]
 [57 49 69]]
[[71 78 62]
 [57 50 66]
 [71 55 71]
 [53 38 76]
 [60 39 72]]
[[75 74 65]
 [75 56 63]
 [57 52 67]
 [48 45 62]
 [56 45 71]]
[[69 75 55]
 [52 44 65]
 [70 50 68]
 [71 66 52]
 [56 52 60]]
[[58 46 69]
 [67 54 62]
 [68 53 69]
 [60 51 65]
 [76 49 72]]
[[64 46 64]
 [48 46 61]
 [56 41 72]
 [56 47 62]
 [63 93 68]]
[[75 67 68]
 [69 79 45]
 [61 80 46]
 [74 50 74]
 [65 73 47]]
[[72 73 62]
 [47 41 64]
 [60 74 55]
 [59 53 60]
 [67 73 53]]
[[63 55 73]
 [70 66 55]
 [74 48 69]
 [75 71 66]
 [81 55 59]]
[[60 73 51]
 [69 77 51]
 [68 67 54]
 [59 49 67]
 [64 48 76]]
[[65 62 68]
 [69 72 69]
 [67 59 62]
 [75 69 68]
 [60 60 61]]
[[61 78 61]
 [55 46 76]
 [59 48 60]
 [84 62 68]
 [75 80 51]]
[[68 79 54]
 [71 67 63]
 [67 75 68]
 [59 50 62]
 [65 69 56]]
[[73 80 55]
 [63 47 50]
 [74 80 55]
 [66 88 68]
 [60 74 50]]
[[46 37 66]
 [70 75 63]
 [45 52 64]
 [69 72 58]
 [67 67 54]]
[[71 54 70]
 [75 51 71]
 [72 60 69]
 [49 41 66]
 [60 68 57]]
[[49 49 54]
 [57 44 56]
